name: Master Quant Trade Bot

on:
  schedule:
    - cron: '30 3 * * 1-5' # 9:00 AM IST
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install yfinance pandas # Only install what strategy_v1.py actually uses

      - name: Run Trading Strategy
        # Removed the API_KEY and API_SECRET env variables
        run: python python_scripts/strategy_v1.py

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
